[funfacts]
title = "Wikipedia â€” did you know?"
url = "https://www.aerzteblatt.de/archiv/suche?s=gyn%E4kologie&titel=&autor=&fg=&jahr=&nr=&seite=&doi=&rss"
entrySelector = ".jsHitlist > .jsHitlistTitle"
titleSelector = "a"
linkSelector = "a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
